### ISSUE TITLE
Figure out how to compile this bot to bytecode and use it like a regular java application

### ISSUE THREAD

**Issue by Nikola1304** [Nikola1304/DiscordBotJava#2]
Please help me, I have no idea how to do this, it compiles but gives me this error:
`Exception in thread "main" java.lang.NoClassDefFoundError: net/dv8tion/jda/api/JDABuilder
        at net.cowtopia.dscjava.Main.main(Main.java:26)
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.api.JDABuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 1 more`

Try something with kotlin, groovy, hell, you can even use maven if you like that. If you can make it work, you will make me really happy

**Comment by TukanDev** [comment]
skill issue hehe

**Comment by Nikola1304** [comment]
I did it
